const codes = require("./codes-loader")


const CV_STATUSES = codes.cv_status
module.exports.CV_STATUS_NOT_STARTED = CV_STATUSES.NOT_STARTED
module.exports.CV_STATUS_STARTED = CV_STATUSES.STARTED
module.exports.CV_STATUS_CANCELED = CV_STATUSES.CANCELED
module.exports.CV_STATUS_FAILED = CV_STATUSES.FAILED
module.exports.CV_STATUS_COMPLETED = CV_STATUSES.COMPLETED


const WEB_STATUSES = codes.web_status
module.exports.WEB_STATUS_OK = WEB_STATUSES.OK
module.exports.WEB_STATUS_INTERNAL_SERVER_ERROR = WEB_STATUSES.INTERNAL_SERVER_ERROR
module.exports.WEB_STATUS_BAD_REQUEST = WEB_STATUSES.BAD_REQUEST
module.exports.WEB_STATUS_NOT_FOUND = WEB_STATUSES.NOT_FOUND
module.exports.WEB_STATUS_FORBIDDEN = WEB_STATUSES.FORBIDDEN